name = "DataGridReader"
uuid = "30c042e5-63fb-47a5-ad35-2a6768182b33"
authors = ["Peter Sabela <=> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
